<?php
require_once __DIR__.'/includes/bootstrap.php';require_login();$uid=(int)user()['user_id'];
$passes=db()->prepare("SELECT er.registration_id,er.registration_status,e.title,e.event_date,e.start_time,e.venue,c.club_name FROM event_registration er JOIN events e ON e.event_id=er.event_id JOIN clubs c ON c.club_id=e.club_id WHERE er.student_user_id=? AND er.registration_status='Registered' ORDER BY e.event_date,e.start_time");$passes->execute([$uid]);$passes=$passes->fetchAll();
$certs=db()->prepare("SELECT cert.certificate_id,cert.certificate_number,cert.issue_date,cert.verification_code,cert.status,e.title,e.event_date,c.club_name FROM certificate cert JOIN attendance a ON a.attendance_id=cert.attendance_id JOIN event_registration er ON er.registration_id=a.registration_id JOIN events e ON e.event_id=er.event_id JOIN clubs c ON c.club_id=e.club_id WHERE er.student_user_id=? ORDER BY cert.issue_date DESC");$certs->execute([$uid]);$certs=$certs->fetchAll();
$pageTitle='Events & certificates';require __DIR__.'/includes/header.php';?>
<section class="page-shell"><div class="page-head"><div><span class="eyebrow">MY PARTICIPATION ARCHIVE</span><h2>Your events.<br><span class="accent-script">Your proof.</span></h2><p>Review upcoming registrations and download verified certificates after attendance is confirmed.</p></div></div>
<div class="section-head"><div><span class="eyebrow">UPCOMING EVENTS</span><h3>Confirmed registrations</h3></div></div><div class="grid pass-grid"><?php foreach($passes as $p):?><article class="card pass-card"><div><span class="card-tag"><?=e($p['club_name'])?></span><h3><?=e($p['title'])?></h3><p><?=e(date('M j, Y',strtotime($p['event_date'])))?> · <?=e(substr($p['start_time'],0,5))?><br><?=e($p['venue'])?></p><small>Registration #<?=$p['registration_id']?> · Confirmed</small></div></article><?php endforeach;?><?php if(!$passes):?><div class="empty">No active registrations. <a class="text-link" href="events.php">Explore events →</a></div><?php endif;?></div>
<div class="section-head"><div><span class="eyebrow">VERIFIED ACHIEVEMENTS</span><h3>Certificates</h3></div></div><div class="agenda"><?php foreach($certs as $c):?><article><div class="event-date-block"><strong><?=e(date('d',strtotime($c['issue_date'])))?></strong><span><?=e(strtoupper(date('M',strtotime($c['issue_date']))))?></span></div><div><h3><?=e($c['title'])?></h3><p><?=e($c['club_name'])?> · <?=e($c['certificate_number'])?></p><a class="text-link" href="verify-certificate.php?code=<?=urlencode($c['verification_code'])?>">Verify publicly →</a></div><span class="badge <?=$c['status']==='Revoked'?'badge-danger':''?>"><?=e($c['status'])?></span><?php if($c['status']==='Active'):?><a class="button button-primary" href="certificate-download.php?id=<?=$c['certificate_id']?>">Download PDF</a><?php endif;?></article><?php endforeach;?><?php if(!$certs):?><div class="empty">Certificates appear here after confirmed attendance.</div><?php endif;?></div></section>
<?php require __DIR__.'/includes/footer.php';?>
