<?php
require_once __DIR__.'/includes/bootstrap.php';require_login();
$uid=(int)user()['user_id'];$admin=is_admin();
$marks=implode(',',array_fill(0,count(executive_roles()),'?'));
$stmt=db()->prepare("SELECT c.club_id,c.club_name,cm.member_role FROM club_membership cm JOIN clubs c ON c.club_id=cm.club_id WHERE cm.student_user_id=? AND cm.approval_status='Approved' AND cm.membership_status='Active' AND cm.member_role IN ($marks)");$stmt->execute(array_merge([$uid],executive_roles()));$managed=$stmt->fetchAll();$executive=!empty($managed);
$stats=['clubs'=>(int)db()->query("SELECT COUNT(*) FROM clubs WHERE status='Active'")->fetchColumn(),'events'=>(int)db()->query("SELECT COUNT(*) FROM events WHERE status IN ('Upcoming','Ongoing')")->fetchColumn(),'memberships'=>0,'managed'=>count($managed)];
$stmt=db()->prepare("SELECT COUNT(*) FROM club_membership WHERE student_user_id=? AND approval_status='Approved' AND membership_status='Active'");$stmt->execute([$uid]);$stats['memberships']=(int)$stmt->fetchColumn();
$stmt=db()->prepare("SELECT e.title,e.event_date,e.start_time,e.venue,c.club_name FROM event_registration er JOIN events e ON e.event_id=er.event_id JOIN clubs c ON c.club_id=e.club_id WHERE er.student_user_id=? AND er.registration_status='Registered' AND e.event_date>=CURDATE() ORDER BY e.event_date,e.start_time LIMIT 4");$stmt->execute([$uid]);$upcoming=$stmt->fetchAll();
$notifications=[];$stmt=db()->prepare("SELECT notification_type,message,created_at,is_read FROM notification WHERE recipient_user_id=? ORDER BY created_at DESC LIMIT 4");$stmt->execute([$uid]);$notifications=$stmt->fetchAll();
$pending=[];$clubEvents=[];
if($executive){$ids=array_column($managed,'club_id');$in=implode(',',array_fill(0,count($ids),'?'));$stmt=db()->prepare("SELECT u.full_name,c.club_name,cm.join_date FROM club_membership cm JOIN users u ON u.user_id=cm.student_user_id JOIN clubs c ON c.club_id=cm.club_id WHERE cm.club_id IN ($in) AND cm.approval_status='Pending' ORDER BY cm.join_date DESC LIMIT 5");$stmt->execute($ids);$pending=$stmt->fetchAll();$stmt=db()->prepare("SELECT e.title,c.club_name,e.maximum_participants,COUNT(er.registration_id) registrations FROM events e JOIN clubs c ON c.club_id=e.club_id LEFT JOIN event_registration er ON er.event_id=e.event_id AND er.registration_status='Registered' WHERE e.club_id IN ($in) GROUP BY e.event_id ORDER BY e.event_date LIMIT 5");$stmt->execute($ids);$clubEvents=$stmt->fetchAll();}
$adminStats=[];$approvalQueue=[];
if($admin){$adminStats=['users'=>(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn(),'pending_clubs'=>(int)db()->query("SELECT COUNT(*) FROM clubs WHERE status='Pending'")->fetchColumn(),'registrations'=>(int)db()->query("SELECT COUNT(*) FROM event_registration WHERE registration_status='Registered'")->fetchColumn(),'feedback'=>(int)db()->query('SELECT COUNT(*) FROM feedback')->fetchColumn()];$approvalQueue=db()->query("SELECT club_name,category,created_at,status FROM clubs WHERE status!='Active' ORDER BY created_at DESC LIMIT 5")->fetchAll();}
$pageTitle='Dashboard';require __DIR__.'/includes/header.php';
?>
<section class="page-shell"><div class="page-head"><div><span class="eyebrow"><?=$admin?'ADMIN EDITION':($executive?'EXECUTIVE DESK':'MY CAMPUS')?></span><h2>Hello, <?=e(explode(' ',user()['full_name'])[0])?>.<br><span class="accent-script"><?=$admin?'Keep it moving.':($executive?'Lead the room.':'What’s next?')?></span></h2><p><?=$admin?'A live operational view of the entire CampusHub community.':($executive?'Memberships, events, and the club signals that need your attention.':'Your registrations, memberships, and latest campus updates.')?></p></div><span class="badge"><?=e(user()['role'])?><?=$executive?' · Executive':''?></span></div>
<?php if($admin):?>
<div class="stat-grid"><div class="stat"><strong><?=$adminStats['users']?></strong><span>Total users</span></div><div class="stat"><strong><?=$stats['clubs']?></strong><span>Active clubs</span></div><div class="stat"><strong><?=$adminStats['registrations']?></strong><span>Registrations</span></div><div class="stat"><strong><?=$stats['events']?></strong><span>Live events</span></div></div>
<div class="dashboard-layout"><section><div class="section-head"><div><span class="eyebrow">MODERATION QUEUE</span><h3>Clubs needing attention</h3></div><a class="text-link" href="clubs.php">Manage all →</a></div><div class="agenda"><?php foreach($approvalQueue as $club):?><article><div class="event-date-block"><strong><?=e(strtoupper(substr($club['club_name'],0,1)))?></strong><span>CLUB</span></div><div><h3><?=e($club['club_name'])?></h3><p><?=e($club['category'])?> · submitted <?=e(date('M j',strtotime($club['created_at'])))?></p></div><span class="badge badge-warn"><?=e($club['status'])?></span></article><?php endforeach;?><?php if(!$approvalQueue):?><div class="empty">The moderation queue is clear.</div><?php endif;?></div></section><aside class="quick-panel"><span class="eyebrow">SYSTEM PULSE</span><a href="clubs.php"><span>◎</span><div><strong><?=$adminStats['pending_clubs']?> pending clubs</strong><small>Review submissions</small></div>→</a><a href="events.php"><span>□</span><div><strong><?=$stats['events']?> current events</strong><small>Monitor the calendar</small></div>→</a><a href="memberships.php"><span>↗</span><div><strong>Membership oversight</strong><small>Review community access</small></div>→</a></aside></div>
<?php elseif($executive):?>
<div class="stat-grid"><div class="stat"><strong><?=count($managed)?></strong><span>Clubs managed</span></div><div class="stat"><strong><?=count($pending)?></strong><span>Pending requests</span></div><div class="stat"><strong><?=count($clubEvents)?></strong><span>Club events</span></div><div class="stat"><strong><?=$stats['memberships']?></strong><span>Your memberships</span></div></div>
<div class="dashboard-layout"><section><div class="section-head"><div><span class="eyebrow">EVENT PULSE</span><h3>Your club calendar</h3></div><a class="text-link" href="events.php?new=1">Create event →</a></div><div class="agenda"><?php foreach($clubEvents as $event):?><article><div class="event-date-block"><strong><?=$event['registrations']?></strong><span>JOINED</span></div><div><h3><?=e($event['title'])?></h3><p><?=e($event['club_name'])?> · capacity <?=$event['maximum_participants']?></p></div><span class="badge"><?=round(($event['registrations']/$event['maximum_participants'])*100)?>% full</span></article><?php endforeach;?></div></section><aside class="quick-panel"><span class="eyebrow">NEEDS ATTENTION</span><?php foreach($pending as $member):?><a href="memberships.php"><span>＋</span><div><strong><?=e($member['full_name'])?></strong><small>Wants to join <?=e($member['club_name'])?></small></div>→</a><?php endforeach;?><?php if(!$pending):?><p>No pending membership requests.</p><?php endif;?></aside></div>
<?php else:?>
<div class="stat-grid"><div class="stat"><strong><?=$stats['clubs']?></strong><span>Active clubs</span></div><div class="stat"><strong><?=$stats['events']?></strong><span>Upcoming events</span></div><div class="stat"><strong><?=$stats['memberships']?></strong><span>Your memberships</span></div><div class="stat"><strong><?=count($notifications)?></strong><span>Recent updates</span></div></div>
<div class="dashboard-layout"><section><div class="section-head"><div><span class="eyebrow">MY AGENDA</span><h3>Coming up for you</h3></div><a class="text-link" href="events.php">Explore more →</a></div><div class="agenda"><?php foreach($upcoming as $event):?><article><div class="event-date-block"><strong><?=e(date('d',strtotime($event['event_date'])))?></strong><span><?=e(strtoupper(date('M',strtotime($event['event_date']))))?></span></div><div><h3><?=e($event['title'])?></h3><p><?=e($event['club_name'])?> · <?=e($event['venue'])?> · <?=e(substr($event['start_time'],0,5))?></p></div><span class="badge">Confirmed</span></article><?php endforeach;?><?php if(!$upcoming):?><div class="empty">No registrations yet. <a class="text-link" href="events.php">Find an event →</a></div><?php endif;?></div></section><aside class="quick-panel"><span class="eyebrow">LATEST UPDATES</span><?php foreach($notifications as $notice):?><a href="#"><span><?=$notice['is_read']?'○':'●'?></span><div><strong><?=e($notice['notification_type'])?></strong><small><?=e($notice['message'])?></small></div></a><?php endforeach;?></aside></div>
<?php endif;?></section>
<?php require __DIR__.'/includes/footer.php';?>
