<?php
require_once __DIR__ . '/includes/bootstrap.php'; require_login();
$uid=(int)user()['user_id'];
$stats=['clubs'=>0,'memberships'=>0,'events'=>0,'managed'=>0];
$stats['clubs']=(int)db()->query("SELECT COUNT(*) FROM clubs WHERE status='Active'")->fetchColumn();
$stats['events']=(int)db()->query("SELECT COUNT(*) FROM events WHERE status IN ('Upcoming','Ongoing')")->fetchColumn();
$s=db()->prepare("SELECT COUNT(*) FROM club_membership WHERE student_user_id=? AND approval_status='Approved' AND membership_status='Active'");$s->execute([$uid]);$stats['memberships']=(int)$s->fetchColumn();
if(is_admin()){$stats['managed']=$stats['clubs'];}else{$marks=implode(',',array_fill(0,count(executive_roles()),'?'));$s=db()->prepare("SELECT COUNT(*) FROM club_membership WHERE student_user_id=? AND approval_status='Approved' AND membership_status='Active' AND member_role IN ($marks)");$s->execute(array_merge([$uid],executive_roles()));$stats['managed']=(int)$s->fetchColumn();}
$s=db()->prepare("SELECT e.title,e.event_date,e.start_time,e.venue,c.club_name,er.registration_status FROM event_registration er JOIN events e ON e.event_id=er.event_id JOIN clubs c ON c.club_id=e.club_id WHERE er.student_user_id=? AND er.registration_status='Registered' AND e.event_date>=CURDATE() ORDER BY e.event_date,e.start_time LIMIT 4");$s->execute([$uid]);$upcoming=$s->fetchAll();
$pageTitle='Dashboard';require __DIR__.'/includes/header.php';
?>
<section class="page-shell"><div class="page-head"><div><span class="eyebrow">Your live dashboard</span><h2>Hello, <?= e(explode(' ',user()['full_name'])[0]) ?>.<br><span class="accent-script">What’s next?</span></h2><p>Here’s what is happening across your campus community.</p></div><span class="badge"><?= e(user()['role']) ?></span></div>
<div class="stat-grid"><div class="stat"><strong><?= $stats['clubs'] ?></strong><span>Active clubs</span></div><div class="stat"><strong><?= $stats['events'] ?></strong><span>Upcoming events</span></div><div class="stat"><strong><?= $stats['memberships'] ?></strong><span>Your memberships</span></div><div class="stat"><strong><?= $stats['managed'] ?></strong><span>Clubs you manage</span></div></div>
<div class="dashboard-layout"><section><div class="section-head"><div><h3>Your upcoming events</h3><p>Registrations update here automatically.</p></div><a class="text-link" href="events.php">Explore more →</a></div><div class="agenda"><?php foreach($upcoming as $event):?><article><div class="event-date-block"><strong><?=e(date('d',strtotime($event['event_date'])))?></strong><span><?=e(strtoupper(date('M',strtotime($event['event_date']))))?></span></div><div><h3><?=e($event['title'])?></h3><p><?=e($event['club_name'])?> · <?=e($event['venue'])?> · <?=e(substr($event['start_time'],0,5))?></p></div><span class="badge">Confirmed</span></article><?php endforeach;?><?php if(!$upcoming):?><div class="empty">No upcoming registrations yet. <a class="text-link" href="events.php">Find an event →</a></div><?php endif;?></div></section><aside class="quick-panel"><span class="eyebrow">Quick actions</span><a href="clubs.php"><span>⌕</span><div><strong>Discover clubs</strong><small>Find your next community</small></div>→</a><a href="memberships.php"><span>◎</span><div><strong>Membership centre</strong><small>Requests and executive roles</small></div>→</a><a href="events.php"><span>＋</span><div><strong>Browse events</strong><small>Register in one click</small></div>→</a></aside></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
